@App_API_HostAddress = http://localhost:5074

###
POST {{App_API_HostAddress}}/remote-agent/weather
Content-Type: application/json
Accept: application/json

{
  "prompt": "Ankara icin bugunku hava durumu nasil?"
}

###
POST {{App_API_HostAddress}}/orchestration/weather-french
Content-Type: application/json
Accept: application/json

{
  "prompt": "Ankara icin bugunku hava durumu nasil?"
}
