// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication.API.Data;

#nullable disable

namespace App.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714183109_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("App.API.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            Description = "High performance laptop",
                            Name = "Laptop X",
                            Price = 1500.00m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            Description = "Latest smartphone with 5G",
                            Name = "Smartphone Y",
                            Price = 999.99m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 3,
                            Category = "Home",
                            Description = "Automatic programmable coffee maker",
                            Name = "Coffee Maker",
                            Price = 80.00m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 4,
                            Category = "Home",
                            Description = "Ergonomic mesh office chair",
                            Name = "Office Chair",
                            Price = 120.50m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 5,
                            Category = "Clothing",
                            Description = "Comfortable running shoes",
                            Name = "Running Shoes",
                            Price = 65.00m,
                            Stock = 75
                        },
                        new
                        {
                            Id = 6,
                            Category = "Clothing",
                            Description = "Cotton plain t-shirt",
                            Name = "T-Shirt",
                            Price = 15.00m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 7,
                            Category = "Books",
                            Description = "Bestselling sci-fi novel",
                            Name = "Science Fiction Book",
                            Price = 12.99m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 8,
                            Category = "Electronics",
                            Description = "Noise-cancelling over-ear headphones",
                            Name = "Headphones",
                            Price = 250.00m,
                            Stock = 40
                        });
                });

            modelBuilder.Entity("WebApplication.API.Data.ChatSessionState", b =>
                {
                    b.Property<string>("ConversationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MessagesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConversationId");

                    b.ToTable("ChatSessionStates");
                });
#pragma warning restore 612, 618
        }
    }
}
